import type { SectionDefinition, SectionType, PropField } from "@/lib/types";

export const SECTION_DEFINITIONS: SectionDefinition[] = [
  {
    type: "header",
    name: "Header",
    description: "Navigation bar with logo and links",
    icon: "layout-navbar",
    defaults: {
      brand: "MyBrand",
      links: "Home, About, Services, Contact",
      ctaText: "Get Started",
      ctaBg: "#6366F1",
    },
  },
  {
    type: "hero",
    name: "Hero",
    description: "Full-width main banner section",
    icon: "photo",
    defaults: {
      title: "Build Something Amazing",
      subtitle:
        "A powerful platform that helps you create beautiful websites without writing a single line of code.",
      btnText: "Start for Free",
      btnBg: "#6366F1",
      bgColor: "#ffffff",
    },
  },
  {
    type: "features",
    name: "Features",
    description: "3-column feature highlights",
    icon: "layout-grid",
    defaults: {
      title: "Why Choose Us",
      subtitle: "Everything you need to build great products",
      bg: "#F8FAFC",
      f1: "Fast Performance",
      f1d: "Blazing fast load times with optimized code and modern infrastructure.",
      f1icon: "⚡",
      f2: "Easy to Use",
      f2d: "Intuitive interface that anyone can master in minutes, not hours.",
      f2icon: "🎯",
      f3: "Secure by Default",
      f3d: "Enterprise-grade security built in from day one, no config needed.",
      f3icon: "🔒",
    },
  },
  {
    type: "testimonials",
    name: "Testimonials",
    description: "Customer reviews and quotes",
    icon: "message-quote",
    defaults: {
      title: "What Our Customers Say",
      q1: "This product changed how we build our website. Absolutely brilliant and highly recommended!",
      a1: "Sarah Chen",
      r1: "CEO, Acme Corp",
      q2: "The best no-code tool I have used in my career as a designer. Worth every penny.",
      a2: "James Okafor",
      r2: "Product Designer, Pixel Studio",
      accentColor: "#6366F1",
    },
  },
  {
    type: "gallery",
    name: "Gallery",
    description: "Responsive image grid",
    icon: "photo-album",
    defaults: {
      title: "Our Work",
      img1: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      img2: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=300&fit=crop",
      img3: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=400&h=300&fit=crop",
      img4: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop",
      img5: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400&h=300&fit=crop",
      img6: "https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=400&h=300&fit=crop",
    },
  },
  {
    type: "contact",
    name: "Contact",
    description: "Contact form with fields",
    icon: "mail",
    defaults: {
      title: "Get in Touch",
      subtitle:
        "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
      bg: "#ffffff",
      btnBg: "#6366F1",
      btnText: "Send Message",
    },
  },
  {
    type: "footer",
    name: "Footer",
    description: "Page footer with links",
    icon: "layout-bottombar",
    defaults: {
      brand: "MyBrand",
      links: "Privacy, Terms, Support",
      copy: "© 2025 MyBrand. All rights reserved.",
      bg: "#0F172A",
    },
  },
];

export const PROP_FIELDS: Record<SectionType, PropField[]> = {
  header: [
    { key: "brand", label: "Brand Name", type: "text" },
    { key: "links", label: "Nav Links (comma-separated)", type: "text" },
    { key: "ctaText", label: "CTA Button Text", type: "text" },
    { key: "ctaBg", label: "Accent Color", type: "color" },
  ],
  hero: [
    { key: "title", label: "Headline", type: "text" },
    { key: "subtitle", label: "Subtitle", type: "textarea" },
    { key: "btnText", label: "Button Text", type: "text" },
    { key: "btnBg", label: "Button Color", type: "color" },
    { key: "bgColor", label: "Background Color", type: "color" },
  ],
  features: [
    { key: "title", label: "Section Title", type: "text" },
    { key: "subtitle", label: "Subtitle", type: "text" },
    { key: "bg", label: "Background Color", type: "color" },
    { key: "f1", label: "Feature 1 Title", type: "text" },
    { key: "f1d", label: "Feature 1 Description", type: "textarea" },
    { key: "f2", label: "Feature 2 Title", type: "text" },
    { key: "f2d", label: "Feature 2 Description", type: "textarea" },
    { key: "f3", label: "Feature 3 Title", type: "text" },
    { key: "f3d", label: "Feature 3 Description", type: "textarea" },
  ],
  testimonials: [
    { key: "title", label: "Section Title", type: "text" },
    { key: "accentColor", label: "Accent Color", type: "color" },
    { key: "q1", label: "Quote 1", type: "textarea" },
    { key: "a1", label: "Author 1 Name", type: "text" },
    { key: "r1", label: "Author 1 Role", type: "text" },
    { key: "q2", label: "Quote 2", type: "textarea" },
    { key: "a2", label: "Author 2 Name", type: "text" },
    { key: "r2", label: "Author 2 Role", type: "text" },
  ],
  gallery: [
    { key: "title", label: "Section Title", type: "text" },
    { key: "img1", label: "Image 1 URL", type: "url" },
    { key: "img2", label: "Image 2 URL", type: "url" },
    { key: "img3", label: "Image 3 URL", type: "url" },
    { key: "img4", label: "Image 4 URL", type: "url" },
    { key: "img5", label: "Image 5 URL", type: "url" },
    { key: "img6", label: "Image 6 URL", type: "url" },
  ],
  contact: [
    { key: "title", label: "Section Title", type: "text" },
    { key: "subtitle", label: "Subtitle", type: "textarea" },
    { key: "bg", label: "Background Color", type: "color" },
    { key: "btnText", label: "Button Text", type: "text" },
    { key: "btnBg", label: "Button Color", type: "color" },
  ],
  footer: [
    { key: "brand", label: "Brand Name", type: "text" },
    { key: "links", label: "Footer Links (comma-separated)", type: "text" },
    { key: "copy", label: "Copyright Text", type: "text" },
    { key: "bg", label: "Background Color", type: "color" },
  ],
};

export const PRESET_COLORS = [
  "#6366F1",
  "#EC4899",
  "#10B981",
  "#F59E0B",
  "#3B82F6",
  "#EF4444",
  "#8B5CF6",
  "#0F172A",
  "#1e293b",
  "#ffffff",
  "#F8FAFC",
];
